# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ICAREdataâ„¢ Study Submission Procedures
email: bobd@mitre.org
description: > # this means to ignore newlines until "baseurl:"
  This site describes the FHIR Messaging based submission procedures for the ICAREdata Study submission infrasturcutre
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mitre.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

mermaid:
  src: 'mermaid.min.js'
